version: 0.2

phases:
  install:
    commands:
      - npm install -g yarn
      - yarn
  build:
    commands:
      - yarn export
artifacts: 
  files:
    - public/**/*
  name: static-next-app-$(date +%Y-%m-%d)

